# Generated by Django 4.2.7 on 2023-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmarket',
            name='redeemed_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmarket',
            name='redeemed_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
