# Generated by Django 4.2.7 on 2023-12-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productmarket_redeemed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmarket',
            name='redeemed_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productmarket',
            name='redeemed_time',
            field=models.TimeField(),
        ),
    ]
