# Generated by Django 4.2.7 on 2023-12-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productmarket_redeemed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmarket',
            name='quantity',
        ),
    ]
