# Generated by Django 4.2.7 on 2023-12-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wholesaler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='product_qrcodes/'),
        ),
    ]
