# Generated by Django 4.2.7 on 2023-12-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmarket',
            name='redeemed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmarket',
            name='redeemed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
