# Generated by Django 4.2.7 on 2024-01-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_customer_number_alter_storeowner_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeowner',
            name='store_location',
        ),
    ]
